name: DreamScoreboard
main: net.perfectdreams.dreamscoreboard.DreamScoreboard
version: 1.0.0
depend: ["DreamCore", "DreamClubes", "DreamChat", "DreamVanish", "DreamBedrockIntegrations"]
api-version: 1.13