name: DreamChat
main: net.perfectdreams.dreamchat.DreamChat
version: 1.0.0
depend: ["DreamCore", "DreamCasamentos", "DreamVote", "DreamMini", "DreamVanish", "DreamClubes", "DreamCash"]
api-version: 1.13
