name: DreamXizum
main: net.perfectdreams.dreamxizum.DreamXizum
version: 1.0.0
softdepend: ["DreamCore", "DreamCash", "DreamChat", "DreamVanish", "Citizens", "HolographicDisplays", "LuckPerms", "mcMMO", "OldCombatMechanics"]
api-version: 1.13