# This is a basic workflow to help you get started with Actions

name: Build SparklyPower Plugins

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13

    - name: Download Paper
      run: wget -O paperclip.jar https://papermc.io/api/v1/paper/1.16.1/10/download
      
    - name: Run Paper
      run: java -Dpaperclip.patchonly=true -jar paperclip.jar
      
    - name: Copy Patched JAR
      run: cp cache/patched_1.16.1.jar libs/
    
    - name: Clone Patched JAR becase some plugins are dumb
      run: cp cache/patched_1.16.1.jar libs/patched_1.15.1.jar
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Runs a single command using the runners shell
    - name: Build DreamCore with Gradle
      run: "./gradlew :DreamCore:build -Dbuild.number=$GITHUB_RUN_NUMBER -Dgit.branch=$GITHUB_REF -Dcommit.hash=$GITHUB_SHA -Dcompiled.at=${{ steps.current-time.outputs.time }}"

    - name: Copy DreamCore to the libs folder
      run: cp DreamCore/build/libs/DreamCore-shadow.jar libs/
      
    # Runs a single command using the runners shell
    - name: Build with Gradle
      run: "./gradlew build -Dbuild.number=$GITHUB_RUN_NUMBER -Dgit.branch=$GITHUB_REF -Dcommit.hash=$GITHUB_SHA -Dcompiled.at=${{ steps.current-time.outputs.time }} --continue --parallel"

    # Upload Artifacts to GitHub
    # Loritta
    - uses: actions/upload-artifact@v2
      name: "Upload Plugins"
      if: ${{ always() }}
      with:
        name: SparklyPower Plugins
        path: "*/build/libs/*.jar"
